<a href="https://colab.research.google.com/github/RuleOfNight/Pytorch_Deep_Learning-study-/blob/main/00.PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource book: https://www.learnpytorch.io

Source code: https://github.com/mrdbourke/pytorch-deep-learning?tab=readme-ov-file

# **1.Cấu trúc và đặc điểm của PyTorch**
a. Tensors (Mãng dữ liệu đa chiều)

* Tensor là cấu trúc dữ liệu cơ bản trong PyTorch, khá giống với mảng (array) trong NumPy nhưng chạy trên GPU nên tốc độ nhanh hơn
* Tính năng nổi bật:
  * Hỗ trợ tính toán nhanh trên CPU và GPU
  * Có thể chuyển đổi dữ liệu qua lại giữa array(NumPy) sang Tensor(PyTorch) và ngược lại

b. Dynamic Computation Graph (Đồ thị tính toán động)
* PyTorch sử dụng **đồ thị tính toán động**, nghĩa là đồ thị này được xây dựng lại tại mỗi vòng lặp test, giúp cho nó dễ dàng thực hiện các phép tính thử nghiệm và linh hoạt trong các mô hình phức tạp

c.Autograd(Đạo hàm tự động)
* Là hệ thống tự động tính gradient(đạo hàm) dựa trên đồ thị tính toán
* Việc tự động đạo hàm giúp giảm độ phức tạp

d.Modules và Layers
* PyTorch cung cấp các lớp `torch.nn` để xây dựng các mạng nơ-ron với nhiều kiểu tầng (layers) như:
  * Tầng tuyến tính (`Linear`)
  * Tầng tích chập (`Conv2d`)
  * Tầng kích hoạt (`ReLU, sigmoid`)

e. GPU Acceleration
* PyTorch tích hợp hỗ trợ GPU, giúp tăng tốc độ huấn luyện mô hình so với chỉ sử dụng CPU
* Lệnh `to(device)` được dùng để chuyển tensor hoặc mô hình sang GPU

# **2. Các thành phần chính của PyTorch**
1. `torch`
* Thư viện chính của PyTorch, cung cấp công cụ xử lý tensor, phép toán tuyến tính,...
2. `torch.nn`
* Module để xây dựng các mô hình mạng nơ-ron
* Tích hợp nhiều loại layer và công cụ huấn luyện
3. `torch.optim`
* Hỗ trợ các thuật toán tối ưu(SGD, Adam, RMSprop) để training
4. `torch.utils.data`
* Công cụ để xử lý và tải dữ liệu, bao gồm các lớp như `Dataset` và `DataLoader`
5. `torchvision`
* Liên quan đến thị giác máy tính (Computer Vision)
  * Bộ dữ liệu: CIFAR-10,MNIST,COCO
  * Các mạng nơ-ron tích chập tiền tập huấn như ResNet, AlexNet



In [ ]:
!nvidia-smi

Wed Nov 20 16:53:19 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Lấy giá trị tensor với kiểu int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0,0:2]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print()
print(TENSOR.ndim)
print()
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

3

torch.Size([1, 3, 3])


# Random tensor

Random tensors quan trọng vì cách mà các neutral network học là bắt đầu với các tensor đầy số ngẫu nhiên và sau đó điều chỉnh những con số ngẫu nhiên đó để biểu thị tốt hơn cho dữ liệu

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
TENSOR = torch.randint(20, size=(4,5))
TENSOR

tensor([[14, 17,  5, 13,  9],
        [ 1, 18,  6,  2, 10],
        [17,  5,  6,  0,  4],
        [12,  0, 10, 18,  4]])

In [ ]:
#Shape imager with tensor
random_img_size_tensor = torch.rand(size=(224,224,3)) # height, width.colour channels(màu RGB)
random_img_size_tensor.shape, random_img_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import torch

random_seed = 19
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.9686, 0.1999, 0.8799, 0.6622],
        [0.2161, 0.1192, 0.3617, 0.0167],
        [0.8503, 0.9620, 0.2479, 0.2946]])
tensor([[0.9686, 0.1999, 0.8799, 0.6622],
        [0.2161, 0.1192, 0.3617, 0.0167],
        [0.8503, 0.9620, 0.2479, 0.2946]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Tensor datatypes
**Note**: Kiểu dữ liệu của tensor là 1 trong 3 lỗi lớn của tensor trong PyTorch và Deep learning:

1. Tensors không đúng kiểu dữ liệu (dtype)
2. Tensors không đúng kích cỡ (shape)
3. Tensors không đúng thiết bị (device)

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.int32,
                               device=None)
float_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

# Các phép toán với tensor

* Cộng
* Trừ
* Nhân (mũ)
* Chia
* Các phép toán ma trận

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
#Cộng
print(tensor +100)
print(torch.add(tensor, 100))

tensor([101, 102, 103])
tensor([101, 102, 103])


In [ ]:
#Trừ
tensor - 2

tensor([-1,  0,  1])

In [ ]:
#Nhân
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [ ]:
#Chia
tensor / 2


tensor([0.5000, 1.0000, 1.5000])

### Matrix Multiplication

In [ ]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.11 ms, sys: 1.89 ms, total: 3 ms
Wall time: 9.85 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.38 ms, sys: 13 µs, total: 1.39 ms
Wall time: 1.45 ms


tensor(14)

In [ ]:
tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensorB = torch.tensor([[1,2,3],
                        [4,5,6]])

print(torch.matmul(tensorA, tensorB))
print(torch.mm(tensorA, tensorB))

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])
tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])


In [ ]:
tensorA.T, tensorA.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [ ]:
tensorA.shape

torch.Size([3, 2])

### Tìm max, min, mean and sum

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x), x.min(), x.argmin()

(tensor(0), tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max(), x.argmax()

(tensor(90), tensor(90), tensor(9))

In [ ]:
#Note: trung bình cộng yêu cầu tensor có kiểu dtype là float32 để sử dụng
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Indexing (chọn data với tensor)

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#taret to tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#middle bracket(dim =1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#last dimension
x[0][0][0]

tensor(1)

# Nói chung là giống NumPy nhưng nạp GPU tăng thời gian chạy

In [ ]:
import torch
import numpy as np
tensor = torch.arange(1,10).reshape(1,3,3)

#Từ PyTorch tensor sang NumPy array:
numpy_array = tensor.numpy()
#Từ NumPy array sang PyTorch tensor:
tensor = torch.from_numpy(numpy_array)

print(tensor)
print()
print(numpy_array)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
